# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='pic_desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='pic_name',
        ),
    ]
