# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=b'Images/None/No-img.jpg', upload_to=b'Images/'),
        ),
    ]
